language: elixir
elixir:
- 1.3.2
before_script:
- phantomjs --wd > /dev/null &
script:
- mix test --exclude failing_on_ci
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: jVvIuTqxRnkzhgDeq+tvit4XH5xl8GjjUhHWH6P+xWoHHcZPMv+1SqVJoWus6SnntwrCPquoHurXppSeyhuKN5gc9+aZJjyBj1X7J8WsGNEgvo89jUbXSV/ZUm4CKYrrEIYib1yFiG0QR7bVe53wUXArlZBnj0HSTLydJhVp9qdgVxeaD3goCk6TayHck5/ClMB8zU5HoIynGnpVBzXjXvk3iexEFZr3bW/FBKpNxaG6vDZIz16Bk8yExQ7fwGaV1eyiEYLGtRxRlqUzr1NFsW4zkW5Lv7yDs4P9i/NNM94Lg1D2n8vDdivZvZUjuvl01bB0er/UClr4ICrsShkTRQX63IE8GuMr2cOGNoBDxPYk1pC7ZZerajzbQ9kU+YZv/Yw72zya4f3xAK+/uEet3MuwdqCtr5Td1IuHI1JA0gYhJHjKY/idU5+mmchOM7Fja/OgmVV8VhO3PVWd6o6aDeYZ/SIZ0GMwG09qKtDp7EsQPkDLajLMYFdPlE0pYXU8ZSCyS93jEkn2s7/lO3WvS20GReBdElLzduekZNblCSG7ehzdSzRizd0FoR1LAZr/AtJJNJcI7NCylYTRByJ8eFaYJ8n7sPHDp1nvMoabI9I8lelHbH7KPmYxDYUvaUQ0S2eUpYfS7L17yQJ5g33cCPu9I+WK04di+5UvWjOS3x4=
  - secure: grOWHJnIeeVpL/qCLeGGTrRiU636IwBCr8UlRYQYOtKl5TWjon1YibdAW2NH1mwsk3sW6OahUbAGRYJEu1QFK1j0rgfpf0EMG2IGY3tNRkVK7hqbgw+Q02V8m9PPMHwQY27YQXc9EQ4ZhDiGsBs3cVvHfRVSNZBrFNMzqAvkV0pv9Hr5PHlJeVmB7bAdS1riiNAgzLawHBVcOPrwflrCR1UX5Sq5jhlJQFcSDXpFHXCD+/cErzdsGct6HX5V+lxiLZmLnEzbMgy3P6gwwVx2MsHwhWidb+fVbVU9YsJrZC0BPYMnY7VfmmvR2F4fxdvec9Ty7lMmYnonSWafBz/96hl/l68NseWXhG8/M0il4Ceufxau7QDQd8xgJjfFFsMjggCWXU0BoDxvug8Ush4LmvoP2wu19mch8pqqWzFcq2Y9peVr6VyHqc5ExVht4IHfwiji8lrm0XGWYF4XMCNrsRw3oKHv3NrZfmkUVb9oabv5Q09D7gtFXF3EN6zCHAYtfUWyL6vPTxYWQqlG9+2wlW63zf2BOzK/UMWe2NJRjiLVbA4w+V8IRiXVeMTq7DZN2M8CTCGmrLIxpQTnaeaVcBU7kywm9mi/bMJSEM/vu2C0HOJpdNAFDKKNUEtL3okfCfkIxD9nPBatblmw8Oux7+uteaiPeDdv8hqKzYDkVkI=
